//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public string Id { get; set; }
        public string MacAddress { get; set; }
        public string IssueDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
